# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Judge group',
            },
        ),
        migrations.CreateModel(
            name='Judge_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Judge groups',
            },
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.Judge_group'),
        ),
    ]
