# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Judge_group',
            new_name='JudgeGroup',
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name_plural': 'Judges'},
        ),
    ]
