# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_auto_20180918_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='judge_group',
        ),
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(default='alskdfjalskdfj309alkjf', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='user_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgegroup',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comps.Judge'),
            preserve_default=False,
        ),
    ]
