# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20181006_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgegroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
